// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: auth.proto

package authpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthValidation_ValidateToken_FullMethodName = "/auth.AuthValidation/ValidateToken"
)

// AuthValidationClient is the client API for AuthValidation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The AuthValidation service definition.
type AuthValidationClient interface {
	// RPC for stateless token validation
	ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error)
}

type authValidationClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthValidationClient(cc grpc.ClientConnInterface) AuthValidationClient {
	return &authValidationClient{cc}
}

func (c *authValidationClient) ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateTokenResponse)
	err := c.cc.Invoke(ctx, AuthValidation_ValidateToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthValidationServer is the server API for AuthValidation service.
// All implementations must embed UnimplementedAuthValidationServer
// for forward compatibility.
//
// The AuthValidation service definition.
type AuthValidationServer interface {
	// RPC for stateless token validation
	ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error)
	mustEmbedUnimplementedAuthValidationServer()
}

// UnimplementedAuthValidationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthValidationServer struct{}

func (UnimplementedAuthValidationServer) ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateToken not implemented")
}
func (UnimplementedAuthValidationServer) mustEmbedUnimplementedAuthValidationServer() {}
func (UnimplementedAuthValidationServer) testEmbeddedByValue()                        {}

// UnsafeAuthValidationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthValidationServer will
// result in compilation errors.
type UnsafeAuthValidationServer interface {
	mustEmbedUnimplementedAuthValidationServer()
}

func RegisterAuthValidationServer(s grpc.ServiceRegistrar, srv AuthValidationServer) {
	// If the following call pancis, it indicates UnimplementedAuthValidationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthValidation_ServiceDesc, srv)
}

func _AuthValidation_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthValidationServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthValidation_ValidateToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthValidationServer).ValidateToken(ctx, req.(*ValidateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthValidation_ServiceDesc is the grpc.ServiceDesc for AuthValidation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthValidation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthValidation",
	HandlerType: (*AuthValidationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateToken",
			Handler:    _AuthValidation_ValidateToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
